version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Cached build dependencies
      - restore_cache:
          keys:
            - requirements-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - requirements-{{ .Branch }}
            - requirements

      - run:
          name: Package installation
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: requirements-{{ .Branch }}-{{ checksum "requirements.txt" }}

  test:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Cached test dependencies
      - restore_cache:
          keys:
            - requirements-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}
            - requirements-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - requirements-{{ .Branch }}
            - requirements

      - run:
          name: CI dependencies installation
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -e .
            pip install -r .circleci/requirements.txt

      - save_cache:
          when: always
          paths:
            - "venv"
          key: requirements-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}

      - run:
          name: Package unit tests
          command: |
            . venv/bin/activate
            coverage run -m unittest discover test/
            coverage xml

      - codecov/upload:
          file: coverage.xml
          flags: unittests

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build