# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files
# https://github.com/conda/conda-build/pull/4480
# for conda-build > 3.21.9
# {% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
# {% set project = pyproject.get('project') %}
# {% set urls = pyproject.get('project', {}).get('urls') %}
package:
  name: pyrovision
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
  fn: pyrovision-{{ environ.get('BUILD_VERSION') }}.tar.gz
  url: ../dist/pyrovision-{{ environ.get('BUILD_VERSION') }}.tar.gz

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python>=3.6, <4.0
    - setuptools

  run:
    - python>=3.6, <4.0
    - pytorch>=1.11.0, <2.0.0
    - torchvision>=0.12.0, <1.0.0
    - tqdm>=4.1.0
    - requests>=2.20.0
    - pylocron>=0.2.0, <1.0.0

test:
  imports:
    - pyrovision
    - pyrovision.models
    - pyrovision.datasets

about:
  home: https://github.com/pyronear/pyro-vision
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Computer vision library for wildfire detection'
  # description: |
  #   {{ data['long_description'] | replace("\n", "\n    ") | replace("#", '\#')}}
  doc_url: https://pyronear.org/pyro-vision
  dev_url: https://github.com/pyronear/pyro-vision
